/* eslint-disable @typescript-eslint/no-require-imports */

/** Third sticker pack (fun): face props, particles (p_), frame pieces (fx_) and picker thumbnails (th_). */
export const AR_SPRITES_V3 = {
  blush_lines: { src: require('../../assets/ar/blush_lines.png'), w: 220, h: 130 },
  buck_teeth: { src: require('../../assets/ar/buck_teeth.png'), w: 279, h: 238 },
  chef_hat: { src: require('../../assets/ar/chef_hat.png'), w: 350, h: 308 },
  emoji_laugh: { src: require('../../assets/ar/emoji_laugh.png'), w: 292, h: 293 },
  emoji_smile: { src: require('../../assets/ar/emoji_smile.png'), w: 294, h: 294 },
  fangs: { src: require('../../assets/ar/fangs.png'), w: 240, h: 110 },
  frog_hat: { src: require('../../assets/ar/frog_hat.png'), w: 344, h: 262 },
  mustache: { src: require('../../assets/ar/mustache.png'), w: 400, h: 137 },
  nerd_glasses: { src: require('../../assets/ar/nerd_glasses.png'), w: 400, h: 149 },
  pixel_shades: { src: require('../../assets/ar/pixel_shades.png'), w: 384, h: 80 },
  sweat_drop: { src: require('../../assets/ar/sweat_drop.png'), w: 87, h: 128 },
  tiger_ears: { src: require('../../assets/ar/tiger_ears.png'), w: 391, h: 243 },
  tiger_muzzle: { src: require('../../assets/ar/tiger_muzzle.png'), w: 392, h: 163 },
  p_bubble: { src: require('../../assets/ar/p_bubble.png'), w: 160, h: 160 },
  p_flame: { src: require('../../assets/ar/p_flame.png'), w: 126, h: 160 },
  p_question: { src: require('../../assets/ar/p_question.png'), w: 105, h: 160 },
  fx_play: { src: require('../../assets/ar/fx_play.png'), w: 160, h: 120 },
  fx_rainbow_beam: { src: require('../../assets/ar/fx_rainbow_beam.png'), w: 144, h: 480 },
  th_baby: { src: require('../../assets/ar/th_baby.png'), w: 112, h: 112 },
  th_big_head: { src: require('../../assets/ar/th_big_head.png'), w: 112, h: 112 },
  th_big_nose: { src: require('../../assets/ar/th_big_nose.png'), w: 112, h: 112 },
  th_color_pop: { src: require('../../assets/ar/th_color_pop.png'), w: 112, h: 112 },
  th_comic: { src: require('../../assets/ar/th_comic.png'), w: 112, h: 112 },
  th_duck_lips: { src: require('../../assets/ar/th_duck_lips.png'), w: 112, h: 112 },
  th_glitch: { src: require('../../assets/ar/th_glitch.png'), w: 112, h: 112 },
  th_hippo: { src: require('../../assets/ar/th_hippo.png'), w: 112, h: 112 },
  th_jelly: { src: require('../../assets/ar/th_jelly.png'), w: 112, h: 112 },
  th_kaleido: { src: require('../../assets/ar/th_kaleido.png'), w: 112, h: 112 },
  th_long_face: { src: require('../../assets/ar/th_long_face.png'), w: 112, h: 112 },
  th_mirror: { src: require('../../assets/ar/th_mirror.png'), w: 112, h: 112 },
  th_pixel: { src: require('../../assets/ar/th_pixel.png'), w: 112, h: 112 },
  th_pop_art: { src: require('../../assets/ar/th_pop_art.png'), w: 112, h: 112 },
  th_puffy: { src: require('../../assets/ar/th_puffy.png'), w: 112, h: 112 },
  th_rainbow: { src: require('../../assets/ar/th_rainbow.png'), w: 112, h: 112 },
  th_swirl: { src: require('../../assets/ar/th_swirl.png'), w: 112, h: 112 },
  th_vhs: { src: require('../../assets/ar/th_vhs.png'), w: 112, h: 112 },
  th_wide_face: { src: require('../../assets/ar/th_wide_face.png'), w: 112, h: 112 },
} as const;
