import type { QuizQuestion } from '@/lib/minigames/travel-quiz-data';
export const QUIZ_QUESTIONS_EXTRA: QuizQuestion[] = [
  {
    id: 'paris-tower',
    question: { ko: '프랑스 파리의 상징적인 철탑은?', en: 'What is the iconic iron tower in Paris, France?' },
    options: { ko: ['에펠탑', '피사의 사탑', '빅벤', '콜로세움'], en: ['Eiffel Tower', 'Leaning Tower', 'Big Ben', 'Colosseum'] },
    correctIndex: 0,
  },
  {
    id: 'great-wall',
    question: { ko: '만리장성이 있는 나라는?', en: 'Which country is home to the Great Wall?' },
    options: { ko: ['중국', '인도', '몽골', '베트남'], en: ['China', 'India', 'Mongolia', 'Vietnam'] },
    correctIndex: 0,
  },
  {
    id: 'australia-capital',
    question: { ko: '호주의 수도는?', en: 'What is the capital of Australia?' },
    options: { ko: ['캔버라', '시드니', '멜버른', '브리즈번'], en: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'] },
    correctIndex: 0,
  },
  {
    id: 'nile-longest',
    question: { ko: '아프리카를 가로지르는 긴 강으로 유명한 것은?', en: 'Which famous river flows through Africa?' },
    options: { ko: ['나일강', '한강', '라인강', '테임즈강'], en: ['Nile', 'Han River', 'Rhine', 'Thames'] },
    correctIndex: 0,
  },
  {
    id: 'kimchi-main',
    question: { ko: '김치의 주 재료로 가장 흔한 채소는?', en: 'What vegetable is most commonly used in kimchi?' },
    options: { ko: ['배추', '오이', '당근', '시금치'], en: ['Napa cabbage', 'Cucumber', 'Carrot', 'Spinach'] },
    correctIndex: 0,
  },
  {
    id: 'taekwondo-origin',
    question: { ko: '태권도가 유래한 나라는?', en: 'Which country is the origin of Taekwondo?' },
    options: { ko: ['한국', '일본', '중국', '태국'], en: ['Korea', 'Japan', 'China', 'Thailand'] },
    correctIndex: 0,
  },
  {
    id: 'mona-lisa',
    question: { ko: '모나리자를 그린 화가는?', en: 'Who painted the Mona Lisa?' },
    options: { ko: ['레오나르도 다 빈치', '피카소', '반 고흐', '모네'], en: ['Leonardo da Vinci', 'Picasso', 'Van Gogh', 'Monet'] },
    correctIndex: 0,
  },
  {
    id: 'earth-core',
    question: { ko: '지구 내부에서 가장 뜨거운 부분은?', en: 'What is the hottest part inside Earth?' },
    options: { ko: ['핵', '맨틀', '외핵', '지각'], en: ['Inner core', 'Mantle', 'Outer core', 'Crust'] },
    correctIndex: 0,
  },
  {
    id: 'piano-keys',
    question: { ko: '표준 피아노 건반 수는?', en: 'How many keys does a standard piano have?' },
    options: { ko: ['88개', '76개', '61개', '92개'], en: ['88', '76', '61', '92'] },
    correctIndex: 0,
  },
  {
    id: 'venice-city',
    question: { ko: '운하와 곤돌라로 유명한 이탈리아 도시는?', en: 'Which Italian city is famous for canals and gondolas?' },
    options: { ko: ['베네치아', '밀라노', '나폴리', '피렌체'], en: ['Venice', 'Milan', 'Naples', 'Florence'] },
    correctIndex: 0,
  },
  {
    id: 'bts-origin',
    question: { ko: 'BTS(방탄소년단)의 활동 기반 국가는?', en: 'Which country is BTS from?' },
    options: { ko: ['대한민국', '미국', '일본', '영국'], en: ['South Korea', 'USA', 'Japan', 'UK'] },
    correctIndex: 0,
  },
  {
    id: 'cheetah-speed',
    question: { ko: '육상에서 가장 빠른 육지 동물은?', en: 'What is the fastest land animal?' },
    options: { ko: ['치타', '사자', '말', '치타 외 토끼'], en: ['Cheetah', 'Lion', 'Horse', 'Rabbit'] },
    correctIndex: 0,
  },
  {
    id: 'statue-liberty',
    question: { ko: '자유의 여신상이 있는 도시는?', en: 'In which city is the Statue of Liberty?' },
    options: { ko: ['뉴욕', '워싱턴 D.C.', '로스앤젤레스', '시카고'], en: ['New York', 'Washington D.C.', 'Los Angeles', 'Chicago'] },
    correctIndex: 0,
  },
  {
    id: 'hangeul-consonants',
    question: { ko: '한글 기본 자음의 개수는?', en: 'How many basic consonants are in Hangul?' },
    options: { ko: ['14개', '10개', '19개', '21개'], en: ['14', '10', '19', '21'] },
    correctIndex: 0,
  },
  {
    id: 'marathon-distance',
    question: { ko: '마라톤의 공식 거리는 약 몇 km?', en: 'What is the official marathon distance (approx.)?' },
    options: { ko: ['42.195km', '21km', '50km', '30km'], en: ['42.195 km', '21 km', '50 km', '30 km'] },
    correctIndex: 0,
  },
  {
    id: 'penguin-region',
    question: { ko: '펭귄이 주로 서식하는 대륙은?', en: 'On which continent do penguins mainly live?' },
    options: { ko: ['남극', '북극', '아프리카', '유럽'], en: ['Antarctica', 'Arctic', 'Africa', 'Europe'] },
    correctIndex: 0,
  },
  {
    id: 'taj-mahal',
    question: { ko: '타지마할이 있는 나라는?', en: 'In which country is the Taj Mahal?' },
    options: { ko: ['인도', '파키스탄', '이란', '네팔'], en: ['India', 'Pakistan', 'Iran', 'Nepal'] },
    correctIndex: 0,
  },
  {
    id: 'water-formula',
    question: { ko: '물의 화학식은?', en: 'What is the chemical formula for water?' },
    options: { ko: ['H₂O', 'CO₂', 'NaCl', 'O₂'], en: ['H₂O', 'CO₂', 'NaCl', 'O₂'] },
    correctIndex: 0,
  },
  {
    id: 'pyeongchang-olympics',
    question: { ko: '2018년 동계올림픽이 열린 한국 도시는?', en: 'Which Korean city hosted the 2018 Winter Olympics?' },
    options: { ko: ['평창', '강릉', '서울', '부산'], en: ['Pyeongchang', 'Gangneung', 'Seoul', 'Busan'] },
    correctIndex: 0,
  },
  {
    id: 'france-capital',
    question: { ko: '프랑스의 수도는?', en: 'What is the capital of France?' },
    options: { ko: ['파리', '리옹', '마르세유', '니스'], en: ['Paris', 'Lyon', 'Marseille', 'Nice'] },
    correctIndex: 0,
  },
  {
    id: 'solar-system-center',
    question: { ko: '태양계의 중심에 있는 천체는?', en: 'What is at the center of our solar system?' },
    options: { ko: ['태양', '지구', '달', '목성'], en: ['The Sun', 'Earth', 'Moon', 'Jupiter'] },
    correctIndex: 0,
  },
  {
    id: 'bulgogi-meat',
    question: { ko: '불고기의 주 재료로 가장 흔한 고기는?', en: 'What meat is most commonly used for bulgogi?' },
    options: { ko: ['소고기', '돼지고기', '닭고기', '양고기'], en: ['Beef', 'Pork', 'Chicken', 'Lamb'] },
    correctIndex: 0,
  },
  {
    id: 'canada-capital',
    question: { ko: '캐나다의 수도는?', en: 'What is the capital of Canada?' },
    options: { ko: ['오타와', '토론토', '밴쿠버', '몬트리올'], en: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'] },
    correctIndex: 0,
  },
  {
    id: 'human-teeth-adult',
    question: { ko: '성인의 영구치 개수는 보통 몇 개?', en: 'How many permanent teeth do adults usually have?' },
    options: { ko: ['32개', '28개', '24개', '36개'], en: ['32', '28', '24', '36'] },
    correctIndex: 0,
  },
  {
    id: 'machu-picchu',
    question: { ko: '마추픽추 유적이 있는 나라는?', en: 'In which country is Machu Picchu?' },
    options: { ko: ['페루', '칠레', '볼리비아', '콜롬비아'], en: ['Peru', 'Chile', 'Bolivia', 'Colombia'] },
    correctIndex: 0,
  },
  {
    id: 'ice-state',
    question: { ko: '물이 얼 때 부피가 어떻게 될까요?', en: 'What happens to water volume when it freezes?' },
    options: { ko: ['약간 늘어난다', '줄어든다', '변하지 않는다', '절반으로 줄어든다'], en: ['Slightly expands', 'Shrinks', 'Stays the same', 'Halves'] },
    correctIndex: 0,
  },
  {
    id: 'uk-capital',
    question: { ko: '영국의 수도는?', en: 'What is the capital of the United Kingdom?' },
    options: { ko: ['런던', '맨체스터', '에든버러', '리버풀'], en: ['London', 'Manchester', 'Edinburgh', 'Liverpool'] },
    correctIndex: 0,
  },
  {
    id: 'hangang-river',
    question: { ko: '서울을 가로지르는 대표적인 강은?', en: 'Which major river flows through Seoul?' },
    options: { ko: ['한강', '낙동강', '금강', '영산강'], en: ['Han River', 'Nakdong', 'Geum', 'Yeongsan'] },
    correctIndex: 0,
  },
  {
    id: 'soccer-players',
    question: { ko: '축구 경기에서 한 팀의 선수 수는?', en: 'How many players does one soccer team have on the field?' },
    options: { ko: ['11명', '9명', '10명', '12명'], en: ['11', '9', '10', '12'] },
    correctIndex: 0,
  },
  {
    id: 'japan-capital',
    question: { ko: '일본의 수도는?', en: 'What is the capital of Japan?' },
    options: { ko: ['도쿄', '오사카', '교토', '삿포로'], en: ['Tokyo', 'Osaka', 'Kyoto', 'Sapporo'] },
    correctIndex: 0,
  },
  {
    id: 'bamboo-panda',
    question: { ko: '대나무를 주로 먹는 동물은?', en: 'Which animal mainly eats bamboo?' },
    options: { ko: ['판다', '코알라', '기린', '코끼리'], en: ['Panda', 'Koala', 'Giraffe', 'Elephant'] },
    correctIndex: 0,
  },
  {
    id: 'seoul-population-country',
    question: { ko: '인구가 세계에서 가장 많은 나라는?', en: 'Which country has the largest population?' },
    options: { ko: ['인도', '미국', '인도네시아', '브라질'], en: ['India', 'USA', 'Indonesia', 'Brazil'] },
    correctIndex: 0,
  },
  {
    id: 'tides-moon',
    question: { ko: '바닷물의 밀물·썰물에 가장 큰 영향을 주는 것은?', en: 'What mainly causes ocean tides?' },
    options: { ko: ['달', '태양', '바람', '지진'], en: ['The Moon', 'The Sun', 'Wind', 'Earthquakes'] },
    correctIndex: 0,
  },
  {
    id: 'german-capital',
    question: { ko: '독일의 수도는?', en: 'What is the capital of Germany?' },
    options: { ko: ['베를린', '뮌헨', '함부르크', '프랑크푸르트'], en: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'] },
    correctIndex: 0,
  },
  {
    id: 'chuncheon-city',
    question: { ko: '닭갈비와 막국수로 유명한 강원도 도시는?', en: 'Which Gangwon city is famous for dakgalbi and makguksu?' },
    options: { ko: ['춘천', '원주', '강릉', '태백'], en: ['Chuncheon', 'Wonju', 'Gangneung', 'Taebaek'] },
    correctIndex: 0,
  },
  {
    id: 'roman-empire-lang',
    question: { ko: '로마 제국에서 널리 쓰인 언어는?', en: 'Which language was widely used in the Roman Empire?' },
    options: { ko: ['라틴어', '그리스어', '프랑스어', '독일어'], en: ['Latin', 'Greek', 'French', 'German'] },
    correctIndex: 0,
  },
  {
    id: 'electricity-unit',
    question: { ko: '전류의 단위는?', en: 'What is the unit of electric current?' },
    options: { ko: ['암페어(A)', '볼트(V)', '와트(W)', '옴(Ω)'], en: ['Ampere (A)', 'Volt (V)', 'Watt (W)', 'Ohm (Ω)'] },
    correctIndex: 0,
  },
  {
    id: 'thailand-capital',
    question: { ko: '태국의 수도는?', en: 'What is the capital of Thailand?' },
    options: { ko: ['방콕', '치앙마이', '푸켓', '파타야'], en: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'] },
    correctIndex: 0,
  },
  {
    id: 'four-seasons',
    question: { ko: '온대 기후에서 일반적으로 구분하는 계절 수는?', en: 'How many seasons are typical in temperate climates?' },
    options: { ko: ['4계절', '2계절', '3계절', '6계절'], en: ['4', '2', '3', '6'] },
    correctIndex: 0,
  },
  {
    id: 'mexico-food',
    question: { ko: '옥수수 과자로 만든 멕시코 대표 음식은?', en: 'Which Mexican food is made from corn tortillas?' },
    options: { ko: ['타코', '스시', '파스타', '크로와상'], en: ['Taco', 'Sushi', 'Pasta', 'Croissant'] },
    correctIndex: 0,
  },
  {
    id: 'computer-memory',
    question: { ko: '컴퓨터가 실행 중인 프로그램을 임시 저장하는 메모리는?', en: 'Which memory temporarily holds running programs?' },
    options: { ko: ['RAM', 'HDD', 'SSD', 'USB'], en: ['RAM', 'HDD', 'SSD', 'USB'] },
    correctIndex: 0,
  },
  {
    id: 'spain-capital',
    question: { ko: '스페인의 수도는?', en: 'What is the capital of Spain?' },
    options: { ko: ['마드리드', '바르셀로나', '세비야', '발렌시아'], en: ['Madrid', 'Barcelona', 'Seville', 'Valencia'] },
    correctIndex: 0,
  },
  {
    id: 'haeundae-beach',
    question: { ko: '부산에서 가장 유명한 해변은?', en: 'What is the most famous beach in Busan?' },
    options: { ko: ['해운대', '광안리', '송정', '다대포'], en: ['Haeundae', 'Gwangalli', 'Songjeong', 'Dadaepo'] },
    correctIndex: 0,
  },
  {
    id: 'human-senses',
    question: { ko: '다음 중 오감에 해당하지 않는 것은?', en: 'Which is NOT one of the five traditional senses?' },
    options: { ko: ['균형감각', '시각', '후각', '미각'], en: ['Balance', 'Sight', 'Smell', 'Taste'] },
    correctIndex: 0,
  },
  {
    id: 'egypt-river',
    question: { ko: '고대 이집트 문명이 발달한 강은?', en: 'Which river nurtured ancient Egyptian civilization?' },
    options: { ko: ['나일강', '티그리스강', '갠지스강', '한강'], en: ['Nile', 'Tigris', 'Ganges', 'Han'] },
    correctIndex: 0,
  },
  {
    id: 'italy-shape',
    question: { ko: '지중해에 위치하며 부츠 모양으로 유명한 나라는?', en: 'Which boot-shaped country borders the Mediterranean?' },
    options: { ko: ['이탈리아', '그리스', '튀르키예', '스페인'], en: ['Italy', 'Greece', 'Turkey', 'Spain'] },
    correctIndex: 0,
  },
  {
    id: 'bible-book-count',
    question: { ko: '1주일은 몇 일?', en: 'How many days are in one week?' },
    options: { ko: ['7일', '5일', '6일', '8일'], en: ['7', '5', '6', '8'] },
    correctIndex: 0,
  },
  {
    id: 'korean-sea-east',
    question: { ko: '한반도 동쪽에 있는 바다의 이름은?', en: 'What is the sea east of the Korean Peninsula?' },
    options: { ko: ['동해', '서해', '남해', '황해'], en: ['East Sea', 'West Sea', 'South Sea', 'Yellow Sea'] },
    correctIndex: 0,
  },
  {
    id: 'volleyball-net',
    question: { ko: '배구 경기에서 양 팀을 가르는 것은?', en: 'What divides the two teams in volleyball?' },
    options: { ko: ['네트(망)', '골대', '벽', '라인'], en: ['Net', 'Goal', 'Wall', 'Line'] },
    correctIndex: 0,
  },
  {
    id: 'newzealand-bird',
    question: { ko: '날지 못하는 대표적인 뉴질랜드 새는?', en: 'Which flightless bird is iconic to New Zealand?' },
    options: { ko: ['키위', '펭귄', '타조', '공작'], en: ['Kiwi', 'Penguin', 'Ostrich', 'Peacock'] },
    correctIndex: 0,
  },
];
